org: netzwerk
app: gen-auth-api
service: gen-auth-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
        - rekognition:DetectFaces
        - dynamodb:PutItem
      Resource:
        - arn:aws:s3:::genauthusers 
        - arn:aws:s3:::genauthusers/*
        - arn:aws:dynamodb:us-east-1:*:table/gen-auth-faceprints 

plugins:
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any

  facedetection:
    handler: ./core/FaceDetection/index.handler
    events:
      - httpApi:
          path: /core/facedetection/{proxy+}
          method: any

  livelinessTracker:
    handler: ./core/LivelinessTracker/index.handler
    events:
      - httpApi:
          path: /core/livetracker/{proxy+}
          method: any

  # Define the S3 trigger function
  s3ImageUpload:
    handler: ./core/IndexFace/index.handler  # Update with your Lambda path
    events:
      - s3:
          bucket: genauthusers  # Your existing S3 bucket name
          event: s3:ObjectCreated:*  # Trigger on object creation
          existing: true  # Since the bucket already exists
